
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Setup critical files for GitHub Pages
        run: |
          # Copy essential files to dist
          cp -f CNAME dist/ || true
          cp -f public/CNAME dist/ || true
          cp -f public/404.html dist/ || true
          cp -f public/robots.txt dist/ || true
          cp -f public/_redirects dist/ || true
          cp -f public/sitemap.xml dist/ || true
          
          # Create .nojekyll file (crucial for GitHub Pages with SPA)
          touch dist/.nojekyll
          
          # Copy image assets
          mkdir -p dist/lovable-uploads
          cp -r public/lovable-uploads/* dist/lovable-uploads/ || true
          
          # Log what has been copied for debugging
          echo "Files in dist directory:"
          ls -la dist/
          echo "Files in lovable-uploads directory:"
          ls -la dist/lovable-uploads/ || true
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
          token: ${{ secrets.GITHUB_TOKEN }}
